In [31]:
import numpy as np
import sys, os
sys.path.append(os.pardir)
from common.util import im2col

In [40]:
x = np.random.randn(3, 2, 4, 4)
w = np.random.randn(4, 2, 2, 2)

In [41]:
col = im2col(x, 2, 2, stride=1, pad=0)

In [42]:
print(col1.shape)

(27, 8)


In [43]:
col_W = w.reshape(4, -1).T
print(col_W.shape)

(8, 4)


In [44]:
out = np.dot(col, col_W)

print(out.shape)

(27, 4)


In [45]:
out = out.reshape(3, 3, 3, -1)

print(out.shape)

(3, 3, 3, 4)


In [58]:
out = out.transpose(0, 3, 1, 2)

print(out)
print(out.shape)

[[[[ 2.15644814e+00 -4.12083202e-04  7.33617306e-01]
   [ 1.24260703e+00  1.19868743e-01 -1.33147226e-01]
   [ 4.25982787e+00  4.53180523e-02 -2.25463043e+00]]

  [[ 7.66543539e-01  3.17219725e+00 -1.93523616e+00]
   [ 2.89116595e+00 -1.34378534e-01  3.33355607e+00]
   [ 6.68680965e-01  1.08924314e+00  7.29026142e-01]]

  [[ 6.14991411e-01  3.60018905e+00 -1.47206071e+00]
   [ 2.25597540e+00  7.08865640e-01  5.89815548e-01]
   [ 5.77223125e-01 -4.61636511e-01  3.85601817e-01]]

  [[ 6.77486565e-01 -5.79296196e-01  5.10085805e+00]
   [-2.18443912e+00 -2.16992244e+00 -1.78941981e+00]
   [ 2.55871217e+00  3.39848866e+00 -3.53504647e+00]]]


 [[[-7.75421824e-01  1.77670977e+00 -1.45356858e+00]
   [-1.06715091e+00 -2.91368528e+00 -2.10356257e+00]
   [ 2.62317958e-01  7.84755244e-02 -3.28865846e+00]]

  [[ 3.61593107e+00 -1.62520145e+00  1.45608804e+00]
   [-3.90815731e-01  3.67116523e-01 -1.46092960e-01]
   [ 1.59395337e+00 -2.36008172e+00  9.21091714e-01]]

  [[ 7.78150877e-01 -5.62106401e

In [59]:
from common.layers import Relu

In [61]:
relu = Relu()
out_relu = relu.forward(out)
print(out_relu)
print(out_relu.shape)

[[[[2.15644814 0.         0.73361731]
   [1.24260703 0.11986874 0.        ]
   [4.25982787 0.04531805 0.        ]]

  [[0.76654354 3.17219725 0.        ]
   [2.89116595 0.         3.33355607]
   [0.66868096 1.08924314 0.72902614]]

  [[0.61499141 3.60018905 0.        ]
   [2.2559754  0.70886564 0.58981555]
   [0.57722312 0.         0.38560182]]

  [[0.67748656 0.         5.10085805]
   [0.         0.         0.        ]
   [2.55871217 3.39848866 0.        ]]]


 [[[0.         1.77670977 0.        ]
   [0.         0.         0.        ]
   [0.26231796 0.07847552 0.        ]]

  [[3.61593107 0.         1.45608804]
   [0.         0.36711652 0.        ]
   [1.59395337 0.         0.92109171]]

  [[0.77815088 0.         0.85364455]
   [1.46097657 0.         0.        ]
   [1.39028864 0.         1.34527701]]

  [[0.         2.05350471 1.71686222]
   [0.         0.         0.        ]
   [0.         2.37786911 0.        ]]]


 [[[0.         4.03415381 1.87785141]
   [0.70411277 2.06183313 0.30

In [62]:
from common.layers import Pooling

In [70]:
pooling = Pooling(pool_h=2, pool_w=2, stride=1)
out_pool = pooling.forward(out_relu)
print(out_pool)
print(out_pool.shape)

[[[[2.15644814 0.73361731]
   [4.25982787 0.11986874]]

  [[3.17219725 3.33355607]
   [2.89116595 3.33355607]]

  [[3.60018905 3.60018905]
   [2.2559754  0.70886564]]

  [[0.67748656 5.10085805]
   [3.39848866 3.39848866]]]


 [[[1.77670977 1.77670977]
   [0.26231796 0.07847552]]

  [[3.61593107 1.45608804]
   [1.59395337 0.92109171]]

  [[1.46097657 0.85364455]
   [1.46097657 1.34527701]]

  [[2.05350471 2.05350471]
   [2.37786911 2.37786911]]]


 [[[4.03415381 4.03415381]
   [2.06183313 2.06183313]]

  [[2.55556077 4.10897883]
   [2.55556077 2.55556077]]

  [[0.87129285 3.60869529]
   [1.47587894 1.47587894]]

  [[2.89260415 2.89260415]
   [2.50429589 2.78399621]]]]
(3, 4, 2, 2)
